// This file should be autogenerated with gyb for security, follow these steps:
// 1. Install gyb with `brew install nshipster/formulae/swift-gyb`
// 2. Uncomment the first Run Script step in build phases (or run gyb by hand)
// 3. If automatically running build step above, export secrets env vars
// by places secrets.sh in the root of this repo that looks like:
// export AIRBASE_APP="appid"
// export AIRBASE_TOKEN="token"
//
// For reference, see: https://nshipster.com/secrets/

internal enum Secrets {

  internal static var airbaseApp: String = "appid"

  internal static var airbaseToken: String = "token"

}
