disabled_rules:
  - multiple_closures_with_trailing_closure
opt_in_rules: # some rules are only opt-in
  - anyobject_protocol
  # Rationale: When using map, we think of it being used to transform a current array into something else
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  # Rationale: A more clear and consise way to check if something exists
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - discouraged_optional_boolean
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - expiring_todo
  - explicit_enum_raw_value
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_name
  - file_name_no_space
  # Rationale: Encourages using the right API to solve a problem
  - first_where
  - flatmap_over_map_reduce
  # - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  # Rationale: Prevents coder error, doesn't crash, makes coder be explicit about their assumptions
  - implicitly_unwrapped_optional
  - indentation_width
  # Rationale: Provides clarity and consistency by using the default parameter
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - no_grouping_extension
  - nslocalizedstring_key
  - nslocalizedstring_require_bundle
  - operator_usage_whitespace
  - optional_enum_case_matching
  # Rationale: Prevents coder error
  - overridden_super_call
  # Rationale: Prevents unpredictable behavior
  - override_in_extension
  # Rationale: Promotes consistency and reduces duplication.
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - strong_iboutlet
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - type_contents_order
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
line_length: 140
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self
  - unused_declaration
  - unused_import
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Directory/*/Secrets.swift
  - DirectoryUITests
  - DirectoryTests